// Generated by `wit-bindgen` 0.20.0. DO NOT EDIT!
// Options used:
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq)]
pub enum Op {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
}
impl ::core::fmt::Debug for Op {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            Op::Add => f.debug_tuple("Op::Add").finish(),
            Op::Sub => f.debug_tuple("Op::Sub").finish(),
            Op::Mul => f.debug_tuple("Op::Mul").finish(),
            Op::Div => f.debug_tuple("Op::Div").finish(),
            Op::Mod => f.debug_tuple("Op::Mod").finish(),
        }
    }
}

impl Op {
    pub(crate) unsafe fn _lift(val: u8) -> Op {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }

        match val {
            0 => Op::Add,
            1 => Op::Sub,
            2 => Op::Mul,
            3 => Op::Div,
            4 => Op::Mod,

            _ => panic!("invalid enum discriminant"),
        }
    }
}

#[allow(unused_unsafe, clippy::all)]
pub fn add(x: i32, y: i32) -> i32 {
    unsafe {
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        extern "C" {
            #[link_name = "add"]
            fn wit_import(_: i32, _: i32) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: i32, _: i32) -> i32 {
            unreachable!()
        }
        let ret = wit_import(_rt::as_i32(&x), _rt::as_i32(&y));
        ret
    }
}
#[allow(unused_unsafe, clippy::all)]
pub fn sub(x: i32, y: i32) -> i32 {
    unsafe {
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        extern "C" {
            #[link_name = "sub"]
            fn wit_import(_: i32, _: i32) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: i32, _: i32) -> i32 {
            unreachable!()
        }
        let ret = wit_import(_rt::as_i32(&x), _rt::as_i32(&y));
        ret
    }
}
#[allow(unused_unsafe, clippy::all)]
pub fn mul(x: i32, y: i32) -> i32 {
    unsafe {
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        extern "C" {
            #[link_name = "mul"]
            fn wit_import(_: i32, _: i32) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: i32, _: i32) -> i32 {
            unreachable!()
        }
        let ret = wit_import(_rt::as_i32(&x), _rt::as_i32(&y));
        ret
    }
}
#[allow(unused_unsafe, clippy::all)]
pub fn div(x: i32, y: i32) -> i32 {
    unsafe {
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        extern "C" {
            #[link_name = "div"]
            fn wit_import(_: i32, _: i32) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: i32, _: i32) -> i32 {
            unreachable!()
        }
        let ret = wit_import(_rt::as_i32(&x), _rt::as_i32(&y));
        ret
    }
}
#[allow(unused_unsafe, clippy::all)]
pub fn mod_(x: i32, y: i32) -> i32 {
    unsafe {
        #[cfg(target_arch = "wasm32")]
        #[link(wasm_import_module = "$root")]
        extern "C" {
            #[link_name = "mod"]
            fn wit_import(_: i32, _: i32) -> i32;
        }

        #[cfg(not(target_arch = "wasm32"))]
        fn wit_import(_: i32, _: i32) -> i32 {
            unreachable!()
        }
        let ret = wit_import(_rt::as_i32(&x), _rt::as_i32(&y));
        ret
    }
}

#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_eval_cabi<T: Guest>(arg0: i32, arg1: i32, arg2: i32) -> i32 {
    let result0 = T::eval(Op::_lift(arg0 as u8), arg1, arg2);
    _rt::as_i32(result0)
}
pub trait Guest {
    fn eval(op: Op, x: i32, y: i32) -> i32;
}
#[doc(hidden)]

macro_rules! __export_world_calculator_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {


    #[export_name = "eval"]
    unsafe extern "C" fn export_eval(arg0: i32,arg1: i32,arg2: i32,) -> i32 {
      $($path_to_types)*::_export_eval_cabi::<$ty>(arg0, arg1, arg2)
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_world_calculator_cabi;
mod _rt {

    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }

    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }

    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }

    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
}

/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_calculator_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::__export_world_calculator_cabi!($ty with_types_in $($path_to_types_root)*);
  )
}
#[doc(inline)]
pub(crate) use __export_calculator_impl as export;

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.20.0:calculator:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 277] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x94\x01\x01A\x02\x01\
A\x0a\x01m\x05\x03add\x03sub\x03mul\x03div\x03mod\x03\0\x02op\x03\0\0\x01@\x02\x01\
xz\x01yz\0z\x03\0\x03add\x01\x02\x03\0\x03sub\x01\x02\x03\0\x03mul\x01\x02\x03\0\
\x03div\x01\x02\x03\0\x03mod\x01\x02\x01@\x03\x02op\x01\x01xz\x01yz\0z\x04\0\x04\
eval\x01\x03\x04\x01\x1fcomponent:calculator/calculator\x04\0\x0b\x10\x01\0\x0ac\
alculator\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.\
201.0\x10wit-bindgen-rust\x060.20.0";

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
